'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")>  _
Partial Friend NotInheritable Class Lemonade
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Lemonade = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Lemonade()),Lemonade)
    
    Public Shared ReadOnly Property [Default]() As Lemonade
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MineTex")>  _
    Public Property Framework() As String
        Get
            Return CType(Me("Framework"),String)
        End Get
        Set
            Me("Framework") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Lemonade")>  _
    Public Property SystemCore() As String
        Get
            Return CType(Me("SystemCore"),String)
        End Get
        Set
            Me("SystemCore") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("settings.json")>  _
    Public Property SettingsFile() As String
        Get
            Return CType(Me("SettingsFile"),String)
        End Get
        Set
            Me("SettingsFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("App.config")>  _
    Public Property ApplicationConfig() As String
        Get
            Return CType(Me("ApplicationConfig"),String)
        End Get
        Set
            Me("ApplicationConfig") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("config.config")>  _
    Public Property CoreConfiguration() As String
        Get
            Return CType(Me("CoreConfiguration"),String)
        End Get
        Set
            Me("CoreConfiguration") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MineTex.vb")>  _
    Public Property MainApplication() As String
        Get
            Return CType(Me("MainApplication"),String)
        End Get
        Set
            Me("MainApplication") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MineTexFramework.php")>  _
    Public Property MainReferenceFile() As String
        Get
            Return CType(Me("MainReferenceFile"),String)
        End Get
        Set
            Me("MainReferenceFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("JSON,C#,VB,L3")>  _
    Public Property MainCodeReference() As String
        Get
            Return CType(Me("MainCodeReference"),String)
        End Get
        Set
            Me("MainCodeReference") = value
        End Set
    End Property
End Class
